name: Build and Release Client Binary

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: Build Client Binary
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true

    - name: Build client binary
      run: cargo build --release --bin client

    - name: Prepare release asset
      run: |
        mkdir release
        cp target\release\client.exe release/

    - name: Upload release asset
      uses: actions/upload-artifact@v3
      with:
        name: client-binary
        path: release/client.exe

  release:
    name: Attach Binary to Release
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download built binary
      uses: actions/download-artifact@v3
      with:
        name: client-binary
        path: release

    - name: Upload to release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: release/client.exe
