name: Build and Release Client and Server Binaries

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-windows:
    name: Build Binaries on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Build client binary
        run: cargo build --release --bin client

      - name: Build server binary
        run: cargo build --release --bin server

      - name: Prepare release assets
        run: |
          mkdir release
          cp target\release\client.exe release/client-windows.exe
          cp target\release\server.exe release/server-windows.exe

      - name: Upload release assets
        uses: actions/upload-artifact@v3
        with:
          name: windows-binaries
          path: release/*

  build-linux:
    name: Build Binaries on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Build client binary
        run: cargo build --release --bin client

      - name: Build server binary
        run: cargo build --release --bin server

      - name: Prepare release assets
        run: |
          mkdir release
          cp target/release/client release/client-linux
          cp target/release/server release/server-linux

      - name: Upload release assets
        uses: actions/upload-artifact@v3
        with:
          name: linux-binaries
          path: release/*

  release:
    name: Attach Binaries to Release
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest

    steps:
      - name: Download Windows binaries
        uses: actions/download-artifact@v3
        with:
          name: windows-binaries
          path: release

      - name: Download Linux binaries
        uses: actions/download-artifact@v3
        with:
          name: linux-binaries
          path: release

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release/client-windows.exe
            release/server-windows.exe
            release/client-linux
            release/server-linux
